[package]
name = "rust-lightning-bitcoinrpc"
version = "0.0.1"
authors = ["Matt Corallo <git@bluematt.me>"]
build = "build.rs"
edition = "2018"

[dependencies]
bitcoin = "0.23"
bitcoin-bech32 = "0.7"
lightning = { git = "https://github.com/TheBlueMatt/rust-lightning", rev = "dac02edc" }
lightning-net-tokio = { git = "https://github.com/TheBlueMatt/rust-lightning", rev = "dac02edc" }
lightning-invoice = { git = "https://github.com/TheBlueMatt/rust-lightning-invoice", rev = "86f1dd0" }
hyper = "0.13"
serde = "1"
serde_json = "1"
serde_derive = "1"
rand = "0.4"
futures-util = "0.3"
tokio = { version = "0.2", features = ["io-std", "io-util", "rt-threaded", "tcp", "time", "sync"] }
base64 = "0.9"
time = "0.2"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[build-dependencies]
cc = "1.0"
