[package]
name = "rust-lightning-bitcoinrpc"
version = "0.0.1"
authors = ["Matt Corallo <git@bluematt.me>"]
build = "build.rs"
edition = "2018"

[dependencies]
bitcoin = "0.21"
bitcoin-bech32 = "0.7"
bitcoin_hashes = "0.7"
lightning = { git = "https://github.com/TheBlueMatt/rust-lightning", rev = "6c367302eba49e30dbd783693fe5b1083e6cc4a0" }
lightning-net-tokio = { git = "https://github.com/TheBlueMatt/rust-lightning", rev = "6c367302eba49e30dbd783693fe5b1083e6cc4a0" }
lightning-invoice = { git = "https://github.com/rust-bitcoin/rust-lightning-invoice", rev = "e738b463d041eb6236997c5f78fd1bc1c612af27" }
secp256k1 = "0.15"
hyper = "0.13"
serde = "1"
serde_json = "1"
serde_derive = "1"
rand = "0.4"
futures-util = "0.3"
tokio = { version = "0.2", features = ["io-std", "io-util", "rt-threaded", "tcp", "time", "sync"] }
base64 = "0.9"

[patch.crates-io]
tokio = { git = "https://github.com/tokio-rs/tokio" }

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[build-dependencies]
cc = "1.0"
